-- Add missing columns to firms table
ALTER TABLE firms ADD COLUMN IF NOT EXISTS registration_number VARCHAR(100);
ALTER TABLE firms ADD COLUMN IF NOT EXISTS website     VARCHAR(255);
ALTER TABLE firms ADD COLUMN IF NOT EXISTS city        VARCHAR(100);
ALTER TABLE firms ADD COLUMN IF NOT EXISTS state       VARCHAR(100);
ALTER TABLE firms ADD COLUMN IF NOT EXISTS pincode     VARCHAR(20);
ALTER TABLE firms ADD COLUMN IF NOT EXISTS country     VARCHAR(100) DEFAULT 'India';
ALTER TABLE firms ADD COLUMN IF NOT EXISTS logo_url    TEXT;
ALTER TABLE firms ADD COLUMN IF NOT EXISTS favicon_url TEXT;
ALTER TABLE firms ADD COLUMN IF NOT EXISTS primary_color VARCHAR(20) DEFAULT '#5B6B7A';
ALTER TABLE firms ADD COLUMN IF NOT EXISTS accent_color  VARCHAR(20) DEFAULT '#3B82F6';

SELECT 'Firms table updated ✓' AS result;
